// exportUtils.js — Universal Export & Download Utility for IntelliDoc AI

import { BASE_URL } from "../api/client";

/**
 * Copy text to clipboard and trigger toast
 */
export function copyToClipboard(text, showToast) {
  if (!text) return;
  const cleanText = typeof text === "string" ? text : JSON.stringify(text, null, 2);
  navigator.clipboard.writeText(cleanText);
  showToast?.("Copied to clipboard", "success");
}

/**
 * Download arbitrary string content as a file
 */
export function downloadFile(filename, content, mimeType = "text/plain") {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export content as PDF via backend or print window fallback
 */
export async function exportPDF(title, content, showToast) {
  const textContent = typeof content === "string" ? content : JSON.stringify(content, null, 2);
  try {
    const res = await fetch(`${BASE_URL}/export/pdf`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title, content: textContent }),
    });

    if (res.ok) {
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${title.toLowerCase().replace(/\s+/g, "_")}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
      showToast?.("PDF exported successfully", "success");
      return;
    }
  } catch (err) {
    console.warn("Backend PDF export failed, using print fallback:", err);
  }

  // Fallback Print Window as PDF
  printContent(title, textContent);
  showToast?.("Opened print window for PDF export", "info");
}

/**
 * Export content as DOCX via backend or blob download
 */
export async function exportDOCX(title, content, showToast) {
  const textContent = typeof content === "string" ? content : JSON.stringify(content, null, 2);
  try {
    const res = await fetch(`${BASE_URL}/export/docx`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title, content: textContent }),
    });

    if (res.ok) {
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${title.toLowerCase().replace(/\s+/g, "_")}.docx`;
      a.click();
      URL.revokeObjectURL(url);
      showToast?.("DOCX exported successfully", "success");
      return;
    }
  } catch (err) {
    console.warn("Backend DOCX export failed, downloading text file:", err);
  }

  // Fallback text download with .docx MIME
  downloadFile(`${title.toLowerCase().replace(/\s+/g, "_")}.docx`, textContent, "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
  showToast?.("Downloaded DOCX document", "success");
}

/**
 * Export content as Markdown
 */
export function exportMarkdown(title, content, showToast) {
  if (!content) return;
  const textContent = typeof content === "string" ? content : JSON.stringify(content, null, 2);
  downloadFile(`${title.toLowerCase().replace(/\s+/g, "_")}.md`, textContent, "text/markdown");
  showToast?.("Downloaded Markdown file", "success");
}

/**
 * Print window helper
 */
export function printContent(title, content) {
  const printWin = window.open("", "_blank");
  if (!printWin) return;

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title} - IntelliDoc AI</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 2rem; color: #1e293b; line-height: 1.6; }
          h1 { color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }
          pre { background: #f8fafc; padding: 1rem; border-radius: 8px; font-family: monospace; white-space: pre-wrap; }
          .footer { margin-top: 2rem; font-size: 0.8rem; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 0.5rem; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div>${typeof content === "string" ? content.replace(/\n/g, "<br/>") : JSON.stringify(content, null, 2)}</div>
        <div class="footer">Generated by IntelliDoc AI Document Intelligence Platform</div>
      </body>
    </html>
  `;

  printWin.document.write(html);
  printWin.document.close();
  printWin.focus();
  setTimeout(() => {
    printWin.print();
    printWin.close();
  }, 250);
}

/**
 * Export Flashcards / Data as CSV
 */
export function exportCSV(title, data, showToast) {
  if (!data) return;
  let csvContent = "";

  if (Array.isArray(data)) {
    if (data.length > 0 && typeof data[0] === "object") {
      const headers = Object.keys(data[0]);
      csvContent += headers.join(",") + "\n";
      data.forEach((row) => {
        const values = headers.map((h) => `"${(row[h] || "").toString().replace(/"/g, '""')}"`);
        csvContent += values.join(",") + "\n";
      });
    } else {
      csvContent = data.join("\n");
    }
  } else {
    csvContent = String(data);
  }

  downloadFile(`${title.toLowerCase().replace(/\s+/g, "_")}.csv`, csvContent, "text/csv");
  showToast?.("Exported CSV file", "success");
}

/**
 * Export Data as JSON
 */
export function exportJSON(title, data, showToast) {
  if (!data) return;
  const jsonContent = JSON.stringify(data, null, 2);
  downloadFile(`${title.toLowerCase().replace(/\s+/g, "_")}.json`, jsonContent, "application/json");
  showToast?.("Exported JSON file", "success");
}
